# Module: prometheus
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.8/metricbeat-module-prometheus.html
- module: prometheus
  #metricsets:
  #  - stats
  period: 10s
  hosts: ["localhost:8889"]
  metrics_path: /metrics
  metrics_filters:
    include: ["antifraud_*", "order_*", "guava_*"]
  use_types: true
  rate_counters: true